# https://quarto.org/docs/manuscripts/components.html
# https://quarto.org/docs/reference/projects/manuscripts.html
# https://quarto.org/docs/reference/projects/options.html

project:
  type: manuscript
  output-dir: "_build" # '_manuscript' by default
  preview:
    port: 4999
    browser: true

  # non-quarto files that should be included with the build:
  resources:
  - data/earthquakes.csv

manuscript:
  article: index.qmd

  manuscript-url: https://gw-ospo.github.io/quarto-manuscript-template

  code-links:
  # example url or local file containing code that produced the research:
  - text: Code Repository
    icon: file-code
    href: https://github.com/gw-ospo/quarto-manuscript-template
  # an example data file used with the research or produced by the research:
  - text: Results File
    icon: file-earmark-spreadsheet
    href: data/earthquakes.csv


format:
  html: default
    #theme: solar
  docx: default
  jats: default
  pdf: default

  #
  # JOURNAL FORMATS:
  # https://quarto.org/docs/extensions/listing-journals.html
  #

  # https://github.com/mikemahoney218/quarto-arxiv
  # quarto install extension mikemahoney218/quarto-arxiv
  #arxiv-pdf:
  #  keep-tex: true

  # https://github.com/quarto-journals/plos#readme
  # quarto install extension quarto-journals/plos docs/
  #plos-pdf:
  #  keep-tex: true
